AccesoDatosCore2023/Models/Empleado.cs
namespace AccesoDatosCore2023.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
    }
}

AccesoDatosCore2023/Models/ErrorViewModel.cs
namespace AccesoDatosCore2023.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AccesoDatosCore2023/Models/Plantilla.cs
namespace AccesoDatosCore2023.Models
{
    public class Plantilla
    {
        public int IdPlantilla { get; set; }
        public string Apellido { get; set; }
        public string Funcion { get; set; }
        public int Salario { get; set; }
        public int HospCod { get; set; }
        public int SalaCod { get; set; }
    }
}

AccesoDatosCore2023/Controllers/EmpleadosController.cs
using AccesoDatosCore2023.Models;
using AccesoDatosCore2023.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Data.SqlClient;

namespace AccesoDatosCore2023.Controllers
{
    public class EmpleadosController : Controller
    {
        //NECESITAMOS NEUSTROS OBJETOS DE BASE DE DATOS
        RepositoryEmpleados repo;

        // EN EL CONSTRUCTOR RECIBIMOS EL REPOSITORIO
        public EmpleadosController(RepositoryEmpleados repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {
            List<Empleado> empleados = repo.GetEmpleados();
            return View(empleados);
        }
        public IActionResult EmpleadosSalario()
        {
            List<Empleado> empleados = repo.GetEmpleados();
            return View(empleados);
        }

        [HttpPost]
        public IActionResult EmpleadosSalario(int salario)
        {
            List<Empleado> empleados = repo.GetEmpleadosSalario(salario);
            return View(empleados);
        }
        public IActionResult Details(int idempleado)
        {
            Empleado empleado = this.repo.FindEmpleado(idempleado);
            return View(empleado);
        }
    }
}

AccesoDatosCore2023/Controllers/HomeController.cs
using AccesoDatosCore2023.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AccesoDatosCore2023.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AccesoDatosCore2023/Controllers/PlantillaController.cs
using AccesoDatosCore2023.Models;
using AccesoDatosCore2023.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace AccesoDatosCore2023.Controllers
{
    public class PlantillaController : Controller
    {
        RepositoryPlantilla repoplantilla;
        public PlantillaController(RepositoryPlantilla repoplantilla)
        {
            this.repoplantilla = repoplantilla;
        }
        public IActionResult Index()
        {
            List<Plantilla> plant = repoplantilla.GetPlantilla();
            return View(plant);
        }
        public IActionResult Details(int idplantilla) 
        {
            Plantilla plant = this.repoplantilla.FindPlantilla(idplantilla);
            return View(plant);
        }
        [HttpPost]
        public IActionResult Index(string funcion)
        {
            List<Plantilla> plantilla = repoplantilla.FindFuncion(funcion);
            return View(plantilla);
        }
    }
}

AccesoDatosCore2023/Views/Empleados/Details.cshtml
@model Empleado
<h1>Apellido: @Model.Apellido</h1>
<h2>Oficio: @Model.Oficio</h2>
<h2>Salario: @Model.Salario</h2>
<h2>ID: @Model.IdEmpleado</h2>
<a asp-controller="Empleados"
asp-action="Index">
Volver al listado
</a>

AccesoDatosCore2023/Views/Empleados/EmpleadosSalario.cshtml
@model List<Empleado>
<h1> Empleados base de datos repository </h1>


<form method="post">
    <label> Introduzca salario</label>
    <input type="text" name="salario" class="form-control" />
    <button class="btn btn-info">
        Buscar empleados
    </button>
</form>


<table class="table table-dark">
    <thead>
        <tr>
            <th>Apellido</th>
            <th>Oficio</th>
            <th>Salario</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Empleado emp in Model)
        {
            <tr>
                <td>@emp.Apellido</td>
                <td>@emp.Oficio</td>
                <td>@emp.Salario</td>
            </tr>
        }
    </tbody>
</table>

AccesoDatosCore2023/Views/Empleados/Index.cshtml
@model List<Empleado>
<h1> Empleados base de datos</h1>


<ul>
    @foreach (Empleado emp in Model)
    {
        <li>@emp.Apellido
        <a asp-controller="Empleados"
        asp-action="Details"
        asp-route-idempleado="@emp.IdEmpleado">
            Detalles</a>
        </li>
    }
</ul>

AccesoDatosCore2023/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AccesoDatosCore2023/Views/Plantilla/Details.cshtml
@model Plantilla
<h1>Apellido: @Model.Apellido</h1>
<h2>Funcion: @Model.Funcion</h2>
<h2>Salario: @Model.Salario</h2>
<h2>ID: @Model.IdPlantilla</h2>
<h2>Codigo Hosp: @Model.HospCod</h2>
<h2>Codigo Sala: @Model.SalaCod</h2>

<a asp-controller="Plantilla"
asp-action="Index">
Volver al listado
</a>

AccesoDatosCore2023/Views/Plantilla/Index.cshtml
@model List<Plantilla>
<h1> Plantilla base de datos repository </h1>


<form method="post">
    <label> Introduzca funcion</label>
    <input type="text" name="funcion" class="form-control" />
    <button class="btn btn-info">
        Buscar por funcion
    </button>
</form>

<table class="table table-dark">
    <thead>
        <tr>
            <th>ID</th>
            <th>Apellido</th>
            <th>Funcion</th>
            <th>Salario</th>
            <th>Detalles</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Plantilla plant in Model)
        {
                <tr>
                    <td>@plant.IdPlantilla</td>
                    <td>@plant.Apellido</td>
                    <td>@plant.Funcion</td>
                    <td>@plant.Salario</td>
                    <td><a asp-controller="Plantilla" asp-action="Details" asp-route-idplantilla="@plant.IdPlantilla"> Ver más</a></td>
                </tr>
        }
    </tbody>
</table>

AccesoDatosCore2023/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AccesoDatosCore2023</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AccesoDatosCore2023.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AccesoDatosCore2023</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados brutos...</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="EmpleadosSalario">Empleados Repository</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantilla" asp-action="Index">Plantilla Repository</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AccesoDatosCore2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>